name: Prebuild
on: [push]
jobs:
  build-test-macos:
    if: github.ref_type == 'tag'
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --mode=skip-build
      - run: yarn test
      # build darwin-x64
      - run: yarn run prebuild-macos
        if: github.ref_type == 'tag'
        env:
          PREBUILD_ARCH: x64
      # build darwin-arm64
      - run: yarn run prebuild-macos
        if: github.ref_type == 'tag'
        env:
          PREBUILD_ARCH: arm64
      - run: tar --create --format ustar --verbose --file=prebuild-darwin-x64-arm64.tar -C prebuilds .
        if: github.ref_type == 'tag'
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: prebuild-darwin-x64-arm64.tar
  build-windows:
    if: github.ref_type == 'tag'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # this will always attempt to use yarn 1
          # cache: yarn
      - run: corepack enable
      # skip the build so we don't die if prebuilts don't already exist (that's
      # why we're building them)
      - run: yarn install --mode=skip-build
      - run: yarn run prebuild-win32
      - run: tar --create --verbose --file=prebuild-win32-x64.tar -C prebuilds .
        if: runner.arch == 'X64'
      - run: tar --create --verbose --file=prebuild-win32-arm64.tar -C prebuilds .
        if: runner.arch == 'ARM64'
        #if: github.ref_type == 'tag'
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: ${{ runner.arch == 'X64' && 'prebuild-win32-x64.tar' || 'prebuild-win32-arm64.tar' }}
  build-linux:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: ldd --version ldd
      - uses: actions/checkout@v3
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --mode=skip-build
      # build linux-x64
      - run: yarn run prebuild-libc
        if: github.ref_type == 'tag'
      # build linux-arm64
      - run: yarn run prebuild-libc
        if: github.ref_type == 'tag'
        env:
          PREBUILD_ARCH: arm64
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
      - run: tar --create --verbose --file=prebuild-linux-x64-arm64.tar -C prebuilds .
      - name: Prebuild
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: prebuild-linux-x64-arm64.tar
